#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Tue Apr 11 21:53:05 2017
#

import wx
import os
import FuncionesReportes as f
import sqlite3 as sq3

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Ingrese la cedula:"))
        self.txtCedula = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Buscar"))

        self.__set_properties()
        self.txtCedula.SetValidator(ContieneDatos())#activa la validacion
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnBuscar, self.button_1)
        self.Bind(wx.EVT_TEXT, self.OnCedula, self.txtCedula)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("Buscar Postulante"))
        self.txtCedula.SetMinSize((150, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_2.Add(self.label_1, 0, 0, 0)
        grid_sizer_2.Add(self.txtCedula, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_1.AddGrowableCol(0)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnCedula(self, event):  # wxGlade: Principal.<event_handler>
        frm=self
        Campo=frm.txtCedula.GetValue()
        
        if len(self.txtCedula.GetValue())>0:
            self.txtCedula.SetBackgroundColour("white")
        
        if len(Campo)<2 and len(Campo)>0:
            if Campo=="E" or Campo=="V" :
                self.txtCedula.SetValue(Campo+"-")
            else:
                dlg=wx.MessageDialog(self,'Debe Ingresar la cedula en el sig. formato V-/E- 0000000', 'Atencion', wx.OK)
                dlg.ShowModal()
                dlg.Destroy()
                self.txtCedula.Clear()
        else:
            if len(Campo)> 10 :
                dlg=wx.MessageDialog(self,'La Cedula no debe ser mayor a 8 caracteres', 'Atencion', wx.OK)
                dlg.ShowModal()
                dlg.Destroy()
                self.txtCedula.Clear()
            else:
                for i in Campo:
                    if chr(69)==i  or chr(86)==i or chr(33)==i or chr(34)==i or chr(35)==i or chr(36)==i or chr(37)==i or chr(38)==i or chr(39)==i or chr(40)==i or chr(41)==i or chr(42)==i or chr(43)==i or chr(44)==i or chr(45)==i or chr(46)==i or chr(47)==i or chr(48)==i or chr(49)==i or chr(50)==i or chr(51)==i or chr(52)==i or chr(53)==i or chr(54)==i or chr(55)==i or chr(56)==i or chr(57)==i or chr(58)==i or chr(59)==i or chr(60)==i or chr(61)==i or chr(62)==i or chr(63)==i:
                        pass
                    else:

                        dlg=wx.MessageDialog(self,'Debe Ingresar Solo Numeros', 'Atencion', wx.OK)
                        dlg.ShowModal()
                        dlg.Destroy()
                        self.txtCedula.Clear()

    
    def OnBuscar(self, event):  # wxGlade: Principal.<event_handler>
        if self.Validate():
            con=sq3.connect('Sisep.s3db')
            con.text_factory=str #pa quitar la U
            cur = con.cursor()
            frm=self
            Ce=frm.txtCedula.GetValue()
            cur.execute("Select * from Postulante where Cedula=:Ce",{"Ce": Ce})
            rs1=cur.fetchone()
            if rs1:
                f.ReportePostulanteI(self)
                os.system('xdg-open "ReportePostulanteIndividual.pdf"') #works for urls too
                self.Hide()
            else:
                dlg=wx.MessageDialog(self,'No se encontro el registro', 'Atencion', wx.OK)
                dlg.ShowModal()
                dlg.Destroy()
                self.txtCedula.Clear()
# end of class Principal
class ContieneDatos(wx.PyValidator):
    def __init__(self):
        wx.PyValidator.__init__(self)

    def Clone(self):
        """
        Note que todo validador debe implementar
        # el método Clone().
        """
        return ContieneDatos()

    def Validate(self, win):
        textCtrl = self.GetWindow()
        text = textCtrl.GetValue()
        if len(text) == 0:
            wx.MessageBox("Este campo debe contener algún texto!",
                          "Error")
            textCtrl.SetBackgroundColour("red")
            textCtrl.SetFocus()
            textCtrl.Refresh()
            return False
        else:
            textCtrl.SetBackgroundColour(
                               wx.SystemSettings_GetColour(
                               wx.SYS_COLOUR_WINDOW))
            textCtrl.Refresh()
            return True

    def TransferToWindow(self):
        return True

    def TransferFromWindow(self):
        return True

