#!/usr/bin/env python
# -*- coding: UTF8 -*-
#
# generated by wxGlade 0.7.1 on Fri Jan  6 18:56:03 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        kwds["style"] = wx.BORDER_NONE | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.estatusbar = self.CreateStatusBar(1)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("12.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_2 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("Inicio_sesion.gif", wx.BITMAP_TYPE_ANY))
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Usuario:"))
        self.txtUsuario = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_3 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("9152064-boton-de-nombre-de-usuario-y-contrasena-ademas-de-inicio-de-sesion-en-un-candado-para-acceso-seguro-.jpg", wx.BITMAP_TYPE_ANY))
        self.label_1_copy = wx.StaticText(self, wx.ID_ANY, _("Clave:"))
        self.txtClave = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Aceptar"))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("Cancelar"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.OnTexto, self.txtUsuario)
        self.Bind(wx.EVT_TEXT, self.OnClave, self.txtClave)
        self.Bind(wx.EVT_BUTTON, self.OnEntrar, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnLimpiar, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("Entrada"))
        self.estatusbar.SetStatusWidths([-1])

        # statusbar fields
        estatusbar_fields = [_(u"Sistema de Simulaci\u00f3n de Cinem\u00e1tica")]
        for i in range(len(estatusbar_fields)):
            self.estatusbar.SetStatusText(estatusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(6, 4, 0, 0)
        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_1, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_2, 0, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.txtUsuario, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_3, 0, 0, 0)
        grid_sizer_1.Add(self.label_1_copy, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.txtClave, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_2.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.AddGrowableCol(2)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnTexto(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnTexto' not implemented!"
        event.Skip()

    def OnClave(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnClave' not implemented!"
        event.Skip()

    def OnEntrar(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnEntrar' not implemented!"
        event.Skip()

    def OnLimpiar(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnLimpiar' not implemented!"
        event.Skip()

# end of class Principal
