#!/usr/bin/env python
# -*- coding: UTF8 -*-
#
# generated by wxGlade 0.7.1 on Sun Apr  9 14:59:29 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.vntPpal_BarraMenu = wx.MenuBar()
        self.archivo = wx.Menu()
        self.principal = wx.MenuItem(self.archivo, wx.ID_ANY, _("Principal"), _("Principal"), wx.ITEM_NORMAL)
        self.archivo.AppendItem(self.principal)
        self.vntPpal_BarraMenu.Append(self.archivo, _("Archivo"))
        self.SetMenuBar(self.vntPpal_BarraMenu)
        # Menu Bar end
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Guardar Postulantes"))
        self.notebook_8 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_8_pane_1 = wx.Panel(self.notebook_8, wx.ID_ANY)
        self.label_9 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Nombres:"))
        self.txtNombre = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_13 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Estado:"))
        self.txtEstado = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_10 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Apellidos:"))
        self.txtApellidos = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_14 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Municipio:"))
        self.txtMunicipio = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_11 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Cedula:"))
        self.txtCedula = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_15 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Parroquia:"))
        self.txtParroquia = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_12 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Sexo:"))
        self.CobSexo = wx.ComboBox(self.notebook_8_pane_1, wx.ID_ANY, choices=[_("M"), _("F")], style=wx.CB_DROPDOWN)
        self.label_16 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Direccion:"))
        self.txtDireccion = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.notebook_9 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_9_pane_1 = wx.Panel(self.notebook_9, wx.ID_ANY)
        self.label_17 = wx.StaticText(self.notebook_9_pane_1, wx.ID_ANY, _("Nivel de Instruccion:"))
        self.combo_box_1 = wx.ComboBox(self.notebook_9_pane_1, wx.ID_ANY, choices=[_("PRIMARIA"), _("PREGRADO"), _("POSTGRADO")], style=wx.CB_DROPDOWN)
        self.label_18 = wx.StaticText(self.notebook_9_pane_1, wx.ID_ANY, _("Especialidad:"))
        self.text_ctrl_1 = wx.TextCtrl(self.notebook_9_pane_1, wx.ID_ANY, "")
        self.label_19 = wx.StaticText(self.notebook_9_pane_1, wx.ID_ANY, _("Idioma:"))
        self.combo_box_2 = wx.ComboBox(self.notebook_9_pane_1, wx.ID_ANY, choices=[_("INGLES"), _("OTROS")], style=wx.CB_DROPDOWN)
        self.notebook_10 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_10_pane_1 = wx.Panel(self.notebook_10, wx.ID_ANY)
        self.label_2 = wx.StaticText(self.notebook_10_pane_1, wx.ID_ANY, _("Salario:"))
        self.cobSalario = wx.ComboBox(self.notebook_10_pane_1, wx.ID_ANY, choices=[_("Salario Minimo"), _("Mayor a Salario Minimo")], style=wx.CB_DROPDOWN)
        self.label_3 = wx.StaticText(self.notebook_10_pane_1, wx.ID_ANY, _("Vigente:"))
        self.cobVigente = wx.ComboBox(self.notebook_10_pane_1, wx.ID_ANY, choices=[_("SI"), _("NO")], style=wx.CB_DROPDOWN)
        self.label_4 = wx.StaticText(self.notebook_10_pane_1, wx.ID_ANY, _("Cargo:"))
        self.cobCargo = wx.ComboBox(self.notebook_10_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Guardar"))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("Limpiar"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnPrincipal, self.principal)
        self.Bind(wx.EVT_TEXT, self.OnLetras, self.txtNombre)
        self.Bind(wx.EVT_TEXT, self.OnLetras, self.txtEstado)
        self.Bind(wx.EVT_TEXT, self.OnLetras, self.txtApellidos)
        self.Bind(wx.EVT_TEXT, self.OnLetras, self.txtMunicipio)
        self.Bind(wx.EVT_TEXT, self.OnCedula, self.txtCedula)
        self.Bind(wx.EVT_BUTTON, self.OnGuardar, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnLimpiar, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("Guardar Postulante"))
        self.SetSize((694, 627))
        self.CobSexo.SetSelection(-1)
        self.combo_box_1.SetMinSize((200, 36))
        self.combo_box_1.SetSelection(-1)
        self.text_ctrl_1.SetMinSize((200, 36))
        self.combo_box_2.SetMinSize((200, 36))
        self.combo_box_2.SetSelection(-1)
        self.cobSalario.SetMinSize((275, 36))
        self.cobSalario.SetSelection(-1)
        self.cobVigente.SetMinSize((275, 36))
        self.cobVigente.SetSelection(-1)
        self.cobCargo.SetMinSize((275, 36))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        grid_sizer_3 = wx.FlexGridSizer(5, 1, 0, 0)
        grid_sizer_2 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(4, 5, 0, 0)
        grid_sizer_3.Add(self.label_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_4.Add(self.label_9, 0, 0, 0)
        grid_sizer_4.Add(self.txtNombre, 0, wx.EXPAND, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add(self.label_13, 0, 0, 0)
        grid_sizer_4.Add(self.txtEstado, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_10, 0, 0, 0)
        grid_sizer_4.Add(self.txtApellidos, 0, wx.EXPAND, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add(self.label_14, 0, 0, 0)
        grid_sizer_4.Add(self.txtMunicipio, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_11, 0, 0, 0)
        grid_sizer_4.Add(self.txtCedula, 0, wx.EXPAND, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add(self.label_15, 0, 0, 0)
        grid_sizer_4.Add(self.txtParroquia, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_12, 0, 0, 0)
        grid_sizer_4.Add(self.CobSexo, 0, wx.EXPAND, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add(self.label_16, 0, 0, 0)
        grid_sizer_4.Add(self.txtDireccion, 0, wx.EXPAND, 0)
        self.notebook_8_pane_1.SetSizer(grid_sizer_4)
        grid_sizer_4.AddGrowableRow(0)
        grid_sizer_4.AddGrowableRow(1)
        grid_sizer_4.AddGrowableRow(2)
        grid_sizer_4.AddGrowableRow(3)
        grid_sizer_4.AddGrowableCol(1)
        grid_sizer_4.AddGrowableCol(4)
        self.notebook_8.AddPage(self.notebook_8_pane_1, _("Datos Personales"))
        grid_sizer_3.Add(self.notebook_8, 1, wx.EXPAND, 0)
        grid_sizer_5.Add(self.label_17, 0, 0, 0)
        grid_sizer_5.Add(self.combo_box_1, 0, 0, 0)
        grid_sizer_5.Add(self.label_18, 0, 0, 0)
        grid_sizer_5.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_5.Add(self.label_19, 0, 0, 0)
        grid_sizer_5.Add(self.combo_box_2, 0, 0, 0)
        self.notebook_9_pane_1.SetSizer(grid_sizer_5)
        grid_sizer_5.AddGrowableCol(1)
        self.notebook_9.AddPage(self.notebook_9_pane_1, _("Educacion"))
        grid_sizer_3.Add(self.notebook_9, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        grid_sizer_1.Add(self.cobSalario, 0, 0, 0)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.cobVigente, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.cobCargo, 0, 0, 0)
        self.notebook_10_pane_1.SetSizer(grid_sizer_1)
        grid_sizer_1.AddGrowableCol(1)
        self.notebook_10.AddPage(self.notebook_10_pane_1, _("Estatus"))
        grid_sizer_3.Add(self.notebook_10, 1, wx.EXPAND, 0)
        grid_sizer_2.Add((150, 20), 0, 0, 0)
        grid_sizer_2.Add(self.button_1, 0, 0, 0)
        grid_sizer_2.Add((50, 20), 0, 0, 0)
        grid_sizer_2.Add(self.button_2, 0, 0, 0)
        grid_sizer_3.Add(grid_sizer_2, 1, 0, 0)
        self.SetSizer(grid_sizer_3)
        grid_sizer_3.AddGrowableRow(1)
        grid_sizer_3.AddGrowableRow(2)
        grid_sizer_3.AddGrowableRow(3)
        grid_sizer_3.AddGrowableCol(0)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnPrincipal(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnPrincipal' not implemented!"
        event.Skip()

    def OnLetras(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnLetras' not implemented!"
        event.Skip()

    def OnCedula(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnCedula' not implemented!"
        event.Skip()

    def OnGuardar(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnGuardar' not implemented!"
        event.Skip()

    def OnLimpiar(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnLimpiar' not implemented!"
        event.Skip()

# end of class Principal
