#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Sun Apr  2 19:38:34 2017
#

import wx
import os
import FuncionesReportes as FR
import SeleccionPostulante as SP
# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Usuarios"))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("Postulantes"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnUsuarios, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnPostulantes, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("Usuarios"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnUsuarios(self, event):  # wxGlade: Principal.<event_handler>
        FR.ReporUsuario(self)
        os.system('xdg-open "ReporteUsuarios.pdf"') #works for urls too

    def OnPostulantes(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=SP.Principal(self)
        Ventana.Show()
        self.Hide()

# end of class Principal
