#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Sun Jan  8 22:29:03 2017
#

import wx
import wx.grid

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        kwds["style"] = wx.BORDER_NONE | wx.MAXIMIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_7 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_7_pane_1 = wx.Panel(self.notebook_7, wx.ID_ANY)
        self.label_23 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_23"))
        self.label_24 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_24"))
        self.label_25 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_25"))
        self.label_26 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_26"))
        self.text_ctrl_10 = wx.TextCtrl(self.notebook_7_pane_1, wx.ID_ANY, "")
        self.text_ctrl_11 = wx.TextCtrl(self.notebook_7_pane_1, wx.ID_ANY, "")
        self.text_ctrl_12 = wx.TextCtrl(self.notebook_7_pane_1, wx.ID_ANY, "")
        self.combo_box_8 = wx.ComboBox(self.notebook_7_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.label_27 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_27"))
        self.label_28 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_28"))
        self.label_29 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_29"))
        self.combo_box_9 = wx.ComboBox(self.notebook_7_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.combo_box_10 = wx.ComboBox(self.notebook_7_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.combo_box_11 = wx.ComboBox(self.notebook_7_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.label_32 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_32"))
        self.label_33 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_33"))
        self.label_34 = wx.StaticText(self.notebook_7_pane_1, wx.ID_ANY, _("label_34"))
        self.text_ctrl_15 = wx.TextCtrl(self.notebook_7_pane_1, wx.ID_ANY, "")
        self.text_ctrl_16 = wx.TextCtrl(self.notebook_7_pane_1, wx.ID_ANY, "")
        self.text_ctrl_17 = wx.TextCtrl(self.notebook_7_pane_1, wx.ID_ANY, "")
        self.grid_1 = wx.grid.Grid(self.notebook_7_pane_1, wx.ID_ANY, size=(1, 1))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("frame_1"))
        self.grid_1.CreateGrid(10, 9)
        self.grid_1.SetColLabelValue(0, _("N Inscripcion"))
        self.grid_1.SetColLabelValue(1, _("C.I"))
        self.grid_1.SetColLabelValue(2, _("Nombre"))
        self.grid_1.SetColLabelValue(3, _("Sexo"))
        self.grid_1.SetColLabelValue(4, _("Edad"))
        self.grid_1.SetColLabelValue(5, _("Casa"))
        self.grid_1.SetColLabelValue(6, _("Municipio"))
        self.grid_1.SetColLabelValue(7, _("Estado"))
        self.grid_1.SetColLabelValue(8, _("Idioma"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_8 = wx.FlexGridSizer(2, 7, 0, 0)
        grid_sizer_7 = wx.FlexGridSizer(2, 7, 0, 0)
        grid_sizer_6 = wx.FlexGridSizer(2, 7, 0, 0)
        grid_sizer_6.Add(self.label_23, 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_24, 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_25, 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_26, 0, 0, 0)
        grid_sizer_6.Add(self.text_ctrl_10, 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.text_ctrl_11, 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.text_ctrl_12, 0, 0, 0)
        grid_sizer_6.Add((20, 20), 0, 0, 0)
        grid_sizer_6.Add(self.combo_box_8, 0, 0, 0)
        grid_sizer_3.Add(grid_sizer_6, 1, 0, 0)
        grid_sizer_7.Add(self.label_27, 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add(self.label_28, 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add(self.label_29, 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add(self.combo_box_9, 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add(self.combo_box_10, 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add(self.combo_box_11, 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_7.Add((20, 20), 0, 0, 0)
        grid_sizer_3.Add(grid_sizer_7, 1, 0, 0)
        grid_sizer_8.Add(self.label_32, 0, 0, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_8.Add(self.label_33, 0, 0, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_8.Add(self.label_34, 0, 0, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_8.Add(self.text_ctrl_15, 0, wx.EXPAND, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_8.Add(self.text_ctrl_16, 0, wx.EXPAND, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_8.Add(self.text_ctrl_17, 0, wx.EXPAND, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_8.Add((20, 20), 0, 0, 0)
        grid_sizer_3.Add(grid_sizer_8, 1, 0, 0)
        sizer_3.Add(grid_sizer_3, 1, 0, 0)
        sizer_3.Add(self.grid_1, 1, wx.EXPAND, 0)
        self.notebook_7_pane_1.SetSizer(sizer_3)
        self.notebook_7.AddPage(self.notebook_7_pane_1, _("Parametros de Filtro"))
        sizer_2.Add(self.notebook_7, 1, 0, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Principal
