#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Sun Apr  9 13:03:10 2017
#

import wx
import os
import funciones as f
import entrada as E
import BuscarExamen as BE
import BuscarPostulantepaso1 as BP1 #No usar
import PrincipalAdmin as PA
import SeleccionPersonal as SPL

#Usuarios
import GuardarUsuario as GU
import BuscarUsuario as BU
import ModificarUsuario as MU

#Bloquear y Desbloquear
import BloquearUsuario as BQU
import DesbloquearUsuario as DU

#Postulante
import SeleccionPostulantes as SP
import GuardarPostulante as GP
import GuardarPostulante2 as GP2
import BuscarPostulante as BP


#Reportes
import MedioUsuarios as MEU
# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        kwds["style"] = wx.MAXIMIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("iconos/Logonuevo.jpg", wx.BITMAP_TYPE_ANY))
        self.notebook_5 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_5_pane_1 = wx.Panel(self.notebook_5, wx.ID_ANY)
        self.bitmap_button_1 = wx.BitmapButton(self.notebook_5_pane_1, wx.ID_ANY, wx.Bitmap("iconos/RegistrarU1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_2 = wx.BitmapButton(self.notebook_5_pane_1, wx.ID_ANY, wx.Bitmap("iconos/BuscarP1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_4 = wx.BitmapButton(self.notebook_5_pane_1, wx.ID_ANY, wx.Bitmap("iconos/ModificarU1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_5 = wx.BitmapButton(self.notebook_5_pane_1, wx.ID_ANY, wx.Bitmap("iconos/Userlock1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_6 = wx.BitmapButton(self.notebook_5_pane_1, wx.ID_ANY, wx.Bitmap("iconos/Userunlock1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_3 = wx.BitmapButton(self.notebook_5_pane_1, wx.ID_ANY, wx.Bitmap("iconos/exit1.png", wx.BITMAP_TYPE_ANY))
        self.notebook_6 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_6_pane_1 = wx.Panel(self.notebook_6, wx.ID_ANY)
        self.bitmap_button_7 = wx.BitmapButton(self.notebook_6_pane_1, wx.ID_ANY, wx.Bitmap("iconos/RegistrarP1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_8 = wx.BitmapButton(self.notebook_6_pane_1, wx.ID_ANY, wx.Bitmap("iconos/BuscarP1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_10 = wx.BitmapButton(self.notebook_6_pane_1, wx.ID_ANY, wx.Bitmap("iconos/Seleccion1.png", wx.BITMAP_TYPE_ANY))
        self.notebook_7 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_7_pane_1 = wx.Panel(self.notebook_7, wx.ID_ANY)
        self.bitmap_button_9 = wx.BitmapButton(self.notebook_7_pane_1, wx.ID_ANY, wx.Bitmap("iconos/ReporU1.png", wx.BITMAP_TYPE_ANY))
        self.notebook_8 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_8_pane_1 = wx.Panel(self.notebook_8, wx.ID_ANY)
        self.bitmap_button_11 = wx.BitmapButton(self.notebook_8_pane_1, wx.ID_ANY, wx.Bitmap("iconos/Informacion1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_12 = wx.BitmapButton(self.notebook_8_pane_1, wx.ID_ANY, wx.Bitmap("iconos/ServicioTecnico1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_13 = wx.BitmapButton(self.notebook_8_pane_1, wx.ID_ANY, wx.Bitmap("iconos/manua1l.png", wx.BITMAP_TYPE_ANY))
        self.label_1 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Usuario:"))
        self.txtUsuario = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        self.label_2 = wx.StaticText(self.notebook_8_pane_1, wx.ID_ANY, _("Fecha:"))
        self.txtFecha = wx.TextCtrl(self.notebook_8_pane_1, wx.ID_ANY, "")
        f.UsuarioFecha(self)
        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnRegistrarU, self.bitmap_button_1)
        self.Bind(wx.EVT_BUTTON, self.OnBuscarU, self.bitmap_button_2)
        self.Bind(wx.EVT_BUTTON, self.OnModificarU, self.bitmap_button_4)
        self.Bind(wx.EVT_BUTTON, self.OnBloquear, self.bitmap_button_5)
        self.Bind(wx.EVT_BUTTON, self.OnDesbloquear, self.bitmap_button_6)
        self.Bind(wx.EVT_BUTTON, self.OnSalir, self.bitmap_button_3)
        self.Bind(wx.EVT_BUTTON, self.OnRegistrarP, self.bitmap_button_7)
        self.Bind(wx.EVT_BUTTON, self.OnBuscarP, self.bitmap_button_8)
        self.Bind(wx.EVT_BUTTON, self.OnSeleccionPersonal, self.bitmap_button_10)
        self.Bind(wx.EVT_BUTTON, self.OnReportes, self.bitmap_button_9)
        self.Bind(wx.EVT_BUTTON, self.OnInformacion, self.bitmap_button_11)
        self.Bind(wx.EVT_BUTTON, self.OnSoporte, self.bitmap_button_12)
        self.Bind(wx.EVT_BUTTON, self.OnManual, self.bitmap_button_13)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("frame_1"))
        self.bitmap_1.SetMinSize((400, 150))
        self.bitmap_button_1.SetMinSize((90, 90))
        self.bitmap_button_1.SetToolTip(wx.ToolTip(_("Registrar Usuario")))
        self.bitmap_button_2.SetMinSize((90, 90))
        self.bitmap_button_2.SetToolTip(wx.ToolTip(_("Buscar Usuario")))
        self.bitmap_button_4.SetMinSize((90, 90))
        self.bitmap_button_4.SetToolTip(wx.ToolTip(_("Modificar Usuario")))
        self.bitmap_button_5.SetMinSize((90, 90))
        self.bitmap_button_5.SetToolTip(wx.ToolTip(_("Bloquear Usuario")))
        self.bitmap_button_6.SetMinSize((90, 90))
        self.bitmap_button_6.SetToolTip(wx.ToolTip(_("Desbloquear Usuario")))
        self.bitmap_button_3.SetToolTip(wx.ToolTip(_("Salir")))
        self.bitmap_button_3.SetSize(self.bitmap_button_3.GetBestSize())
        self.bitmap_button_7.SetMinSize((90, 90))
        self.bitmap_button_7.SetToolTip(wx.ToolTip(_("Registrar Postulante")))
        self.bitmap_button_8.SetMinSize((90, 90))
        self.bitmap_button_8.SetToolTip(wx.ToolTip(_("Buscar Postulante")))
        self.bitmap_button_10.SetMinSize((90, 90))
        self.bitmap_button_10.SetToolTip(wx.ToolTip(_("Seleccion de Postulantes")))
        self.bitmap_button_9.SetMinSize((90, 90))
        self.bitmap_button_9.SetToolTip(wx.ToolTip(_("Reportes")))
        self.bitmap_button_11.SetMinSize((90, 90))
        self.bitmap_button_11.SetToolTip(wx.ToolTip(_("Informacion")))
        self.bitmap_button_12.SetMinSize((90, 90))
        self.bitmap_button_12.SetToolTip(wx.ToolTip(_("Soporte Tecnico")))
        self.bitmap_button_13.SetMinSize((90, 90))
        self.bitmap_button_13.SetToolTip(wx.ToolTip(_("Manuales")))
        self.txtUsuario.Enable(False)
        self.txtFecha.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(5, 1, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(1, 7, 0, 0)
        grid_sizer_6 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(1, 1, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(1, 5, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 12, 0, 0)
        grid_sizer_1.Add(self.bitmap_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.bitmap_button_1, 0, 0, 0)
        grid_sizer_2.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.bitmap_button_2, 0, 0, 0)
        grid_sizer_2.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.bitmap_button_4, 0, 0, 0)
        grid_sizer_2.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.bitmap_button_5, 0, 0, 0)
        grid_sizer_2.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.bitmap_button_6, 0, 0, 0)
        grid_sizer_2.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.bitmap_button_3, 0, wx.ALIGN_RIGHT, 0)
        self.notebook_5_pane_1.SetSizer(grid_sizer_2)
        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableCol(10)
        self.notebook_5.AddPage(self.notebook_5_pane_1, _("Usuarios"))
        grid_sizer_1.Add(self.notebook_5, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.bitmap_button_7, 0, 0, 0)
        grid_sizer_3.Add((20, 20), 0, 0, 0)
        grid_sizer_3.Add(self.bitmap_button_8, 0, 0, 0)
        grid_sizer_3.Add((20, 20), 0, 0, 0)
        grid_sizer_3.Add(self.bitmap_button_10, 0, 0, 0)
        self.notebook_6_pane_1.SetSizer(grid_sizer_3)
        grid_sizer_3.AddGrowableRow(0)
        self.notebook_6.AddPage(self.notebook_6_pane_1, _("Postulantes"))
        grid_sizer_1.Add(self.notebook_6, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.bitmap_button_9, 0, 0, 0)
        self.notebook_7_pane_1.SetSizer(grid_sizer_4)
        grid_sizer_4.AddGrowableRow(0)
        self.notebook_7.AddPage(self.notebook_7_pane_1, _("Reportes"))
        grid_sizer_1.Add(self.notebook_7, 1, wx.EXPAND, 0)
        grid_sizer_5.Add(self.bitmap_button_11, 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add(self.bitmap_button_12, 0, 0, 0)
        grid_sizer_5.Add((20, 20), 0, 0, 0)
        grid_sizer_5.Add(self.bitmap_button_13, 0, 0, 0)
        grid_sizer_5.Add((800, 20), 0, 0, 0)
        grid_sizer_6.Add(self.label_1, 0, 0, 0)
        grid_sizer_6.Add(self.txtUsuario, 0, 0, 0)
        grid_sizer_6.Add(self.label_2, 0, 0, 0)
        grid_sizer_6.Add(self.txtFecha, 0, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, 0, 0)
        self.notebook_8_pane_1.SetSizer(grid_sizer_5)
        grid_sizer_5.AddGrowableRow(0)
        self.notebook_8.AddPage(self.notebook_8_pane_1, _("Informacion"))
        grid_sizer_1.Add(self.notebook_8, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        grid_sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def OnRegistrarU(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=GU.Principal(self)
        Ventana.Show()
    def OnBuscarU(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=BU.Principal(self)
        Ventana.Show()

    def OnEditarU(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=MU.Principal(self)
        Ventana.Show()

    def OnBloquear(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=BQU.Principal(self)
        Ventana.Show()

    def OnDesbloquear(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=DU.Principal(self)
        Ventana.Show()
        

    def OnSalir(self, event):  # wxGlade: Principal.<event_handler>
        
    #wx.InitAllImageHandlers()
        
        dlg = wx.MessageDialog(None, '¿Desea Salir?',
                           'Dialogo de Mensage', wx.OK|wx.CANCEL|
                            wx.ICON_QUESTION)
        #dlg.ShowModal()
        

        if dlg.ShowModal()==wx.ID_OK:
                  
            
            Ventana=E.Principal(self)
            Ventana.Show()
            self.Hide()
                        
            
            
        dlg.Destroy() 

        

    def OnRegistrarP(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=SP.Principal(self)
        Ventana.Show()
    def OnBuscarP(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=BP.Principal(self)
        Ventana.Show()

    def OnReportes(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=MEU.Principal(self)
        Ventana.Show()

    def OnExamen(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=BE.Principal(self)
        Ventana.Show()
    def OnInformacion(self, event):  # wxGlade: Principal.<event_handler>
        os.system('xdg-open "Informacion.pdf"')
    def OnSoporte(self, event):  # wxGlade: Principal.<event_handler>
        os.system('xdg-open "SoporteTecnico.pdf"')
    def OnModificarU(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=MU.Principal(self)
        Ventana.Show()
    def OnManual(self, event):  # wxGlade: Principal.<event_handler>
        os.system('xdg-open "ManualAdmin.pdf"')
    def OnSeleccionPersonal(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=SPL.Principal(self)
        Ventana.Show()
# end of class Principal
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.App()
    #wx.InitAllImageHandlers()
    frame_1 = Principal(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
