#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Thu Jun  1 09:27:04 2017
#

import wx
import os
import funciones as f
import entrada as E
import BuscarExamen as BE
import BuscarPostulantepaso1 as BP1 #No usar

#Usuarios
import GuardarUsuario as GU
import BuscarUsuario as BU
import ModificarUsuario as MU

#Bloquear y Desbloquear
import BloquearUsuario as BQU
import DesbloquearUsuario as DU

#Postulante
import MedioUsuarios as MEU
import SeleccionPostulantes as SP
import GuardarPostulante as GP
import GuardarPostulante2 as GP2
import BuscarPostulante as BP
# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        kwds["style"] = wx.MAXIMIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("iconos/Logonuevo.jpg", wx.BITMAP_TYPE_ANY))
        self.notebook_2 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_2_pane_1 = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.bitmap_button_9 = wx.BitmapButton(self.notebook_2_pane_1, wx.ID_ANY, wx.Bitmap("iconos/RegistrarP1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_8 = wx.BitmapButton(self.notebook_2_pane_1, wx.ID_ANY, wx.Bitmap("iconos/BuscarP1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_1 = wx.BitmapButton(self.notebook_2_pane_1, wx.ID_ANY, wx.Bitmap("iconos/exit1.png", wx.BITMAP_TYPE_ANY))
        self.notebook_3 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_3_pane_1 = wx.Panel(self.notebook_3, wx.ID_ANY)
        self.bitmap_button_10 = wx.BitmapButton(self.notebook_3_pane_1, wx.ID_ANY, wx.Bitmap("iconos/ReporU1.png", wx.BITMAP_TYPE_ANY))
        self.notebook_4 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_4_pane_1 = wx.Panel(self.notebook_4, wx.ID_ANY)
        self.bitmap_button_11 = wx.BitmapButton(self.notebook_4_pane_1, wx.ID_ANY, wx.Bitmap("iconos/Informacion1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_12 = wx.BitmapButton(self.notebook_4_pane_1, wx.ID_ANY, wx.Bitmap("iconos/ServicioTecnico1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_2 = wx.BitmapButton(self.notebook_4_pane_1, wx.ID_ANY, wx.Bitmap("iconos/manua1l.png", wx.BITMAP_TYPE_ANY))
        self.label_1 = wx.StaticText(self.notebook_4_pane_1, wx.ID_ANY, _("Usuario:"))
        self.txtUsuario = wx.TextCtrl(self.notebook_4_pane_1, wx.ID_ANY, "")
        self.label_2 = wx.StaticText(self.notebook_4_pane_1, wx.ID_ANY, _("Fecha:"))
        self.txtFecha = wx.TextCtrl(self.notebook_4_pane_1, wx.ID_ANY, "")
        f.UsuarioFecha(self)
        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnRegistrarP, self.bitmap_button_9)
        self.Bind(wx.EVT_BUTTON, self.OnBuscarP, self.bitmap_button_8)
        self.Bind(wx.EVT_BUTTON, self.OnSalir, self.bitmap_button_1)
        self.Bind(wx.EVT_BUTTON, self.OnReportes, self.bitmap_button_10)
        self.Bind(wx.EVT_BUTTON, self.OnInformacion, self.bitmap_button_11)
        self.Bind(wx.EVT_BUTTON, self.OnSoporte, self.bitmap_button_12)
        self.Bind(wx.EVT_BUTTON, self.OnManual, self.bitmap_button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("frame_1"))
        self.bitmap_button_9.SetToolTip(wx.ToolTip(_("Registrar Postulante")))
        self.bitmap_button_9.SetSize(self.bitmap_button_9.GetBestSize())
        self.bitmap_button_8.SetToolTip(wx.ToolTip(_("Buscar Postulante")))
        self.bitmap_button_8.SetSize(self.bitmap_button_8.GetBestSize())
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        self.notebook_2.SetMinSize((400, 159))
        self.bitmap_button_10.SetToolTip(wx.ToolTip(_("Reportes")))
        self.bitmap_button_10.SetSize(self.bitmap_button_10.GetBestSize())
        self.bitmap_button_11.SetSize(self.bitmap_button_11.GetBestSize())
        self.bitmap_button_12.SetToolTip(wx.ToolTip(_("Soporte Tecnico")))
        self.bitmap_button_12.SetSize(self.bitmap_button_12.GetBestSize())
        self.bitmap_button_2.SetToolTip(wx.ToolTip(_("Manuales")))
        self.bitmap_button_2.SetSize(self.bitmap_button_2.GetBestSize())
        self.txtUsuario.Enable(False)
        self.txtFecha.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4 = wx.FlexGridSizer(1, 8, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 6, 0, 0)
        sizer_1.Add(self.bitmap_1, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.bitmap_button_9, 0, 0, 0)
        grid_sizer_2.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.bitmap_button_8, 0, 0, 0)
        grid_sizer_2.Add((20, 20), 0, 0, 0)
        grid_sizer_2.Add(self.bitmap_button_1, 0, wx.ALIGN_RIGHT, 0)
        self.notebook_2_pane_1.SetSizer(grid_sizer_2)
        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableCol(4)
        self.notebook_2.AddPage(self.notebook_2_pane_1, _("Postulantes"))
        sizer_1.Add(self.notebook_2, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.bitmap_button_10, 0, 0, 0)
        self.notebook_3_pane_1.SetSizer(grid_sizer_3)
        self.notebook_3.AddPage(self.notebook_3_pane_1, _("Reportes"))
        sizer_1.Add(self.notebook_3, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.bitmap_button_11, 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add(self.bitmap_button_12, 0, 0, 0)
        grid_sizer_4.Add((20, 20), 0, 0, 0)
        grid_sizer_4.Add(self.bitmap_button_2, 0, 0, 0)
        grid_sizer_4.Add((700, 20), 0, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.txtUsuario, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        grid_sizer_1.Add(self.txtFecha, 0, 0, 0)
        grid_sizer_4.Add(grid_sizer_1, 1, 0, 0)
        self.notebook_4_pane_1.SetSizer(grid_sizer_4)
        self.notebook_4.AddPage(self.notebook_4_pane_1, _("Informacion"))
        sizer_1.Add(self.notebook_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnRegistrarU(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnRegistrarU' not implemented!"
        event.Skip()

    def OnBuscarU(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnBuscarU' not implemented!"
        event.Skip()

    def OnEditarU(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnEditarU' not implemented!"
        event.Skip()

    def OnBloquear(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnBloquear' not implemented!"
        event.Skip()

    def OnDesbloquear(self, event):  # wxGlade: Principal.<event_handler>
        print "Event handler 'OnDesbloquear' not implemented!"
        event.Skip()

    def OnSalir(self, event):  # wxGlade: Principal.<event_handler>
        dlg = wx.MessageDialog(None, '¿Desea Salir?',
                           'Dialogo de Mensage', wx.OK|wx.CANCEL|
                            wx.ICON_QUESTION)
        #dlg.ShowModal()
        

        if dlg.ShowModal()==wx.ID_OK:
            Ventana=E.Principal(self)
            Ventana.Show()
            self.Hide()
        dlg.Destroy()  

    def OnRegistrarP(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=SP.Principal(self)
        Ventana.Show()

    def OnBuscarP(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=BP.Principal(self)
        Ventana.Show()

    def OnExamen(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=BE.Principal(self)
        Ventana.Show()

    def OnReportes(self, event):  # wxGlade: Principal.<event_handler>
        Ventana=MEU.Principal(self)
        Ventana.Show()

    def OnInformacion(self, event):  # wxGlade: Principal.<event_handler>
        os.system('xdg-open "Informacion.pdf"')
    def OnSoporte(self, event):  # wxGlade: Principal.<event_handler>
        os.system('xdg-open "SoporteTecnico.pdf"')

    def OnManual(self, event):  # wxGlade: Principal.<event_handler>
       os.system('xdg-open "ManualAdmin.pdf"')
# end of class Principal
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.App()
    #wx.InitAllImageHandlers()
    frame_1 = Principal(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()