#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Mon Apr  3 23:43:11 2017
#

import wx
import os
import FuncionesReportes as FR
# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Principal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Principal.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_button_1 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/Administrativo1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_3 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/chofer1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_4 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/GerenteVentas1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_5 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/cash_register_2561.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_9 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/AtencionCliente1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_2 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/Vigilante1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_7 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/Vendedor1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_8 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/Asistente1.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_6 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("iconos/RecursosHumanos1.jpg", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAdministrativo, self.bitmap_button_1)
        self.Bind(wx.EVT_BUTTON, self.OnChofer, self.bitmap_button_3)
        self.Bind(wx.EVT_BUTTON, self.OnAVentas, self.bitmap_button_4)
        self.Bind(wx.EVT_BUTTON, self.OnCajero, self.bitmap_button_5)
        self.Bind(wx.EVT_BUTTON, self.OnAtencionC, self.bitmap_button_9)
        self.Bind(wx.EVT_BUTTON, self.OnVigilante, self.bitmap_button_2)
        self.Bind(wx.EVT_BUTTON, self.OnGVentas, self.bitmap_button_7)
        self.Bind(wx.EVT_BUTTON, self.OnAsistenteA, self.bitmap_button_8)
        self.Bind(wx.EVT_BUTTON, self.OnRecursos, self.bitmap_button_6)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Principal.__set_properties
        self.SetTitle(_("Seleccion de Postulantes"))
        self.bitmap_button_1.SetToolTip(wx.ToolTip(_("Administrativo")))
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        self.bitmap_button_3.SetToolTip(wx.ToolTip(_("Chofer")))
        self.bitmap_button_3.SetSize(self.bitmap_button_3.GetBestSize())
        self.bitmap_button_4.SetToolTip(wx.ToolTip(_("Asistente de Ventas")))
        self.bitmap_button_4.SetSize(self.bitmap_button_4.GetBestSize())
        self.bitmap_button_5.SetToolTip(wx.ToolTip(_("Cajero")))
        self.bitmap_button_5.SetSize(self.bitmap_button_5.GetBestSize())
        self.bitmap_button_9.SetToolTip(wx.ToolTip(_("Atencion al Cliente")))
        self.bitmap_button_9.SetSize(self.bitmap_button_9.GetBestSize())
        self.bitmap_button_2.SetToolTip(wx.ToolTip(_("Vigilante")))
        self.bitmap_button_2.SetSize(self.bitmap_button_2.GetBestSize())
        self.bitmap_button_7.SetToolTip(wx.ToolTip(_("Gerente de Ventas")))
        self.bitmap_button_7.SetSize(self.bitmap_button_7.GetBestSize())
        self.bitmap_button_8.SetToolTip(wx.ToolTip(_("Asistente Administrativo")))
        self.bitmap_button_8.SetSize(self.bitmap_button_8.GetBestSize())
        self.bitmap_button_6.SetToolTip(wx.ToolTip(_("Recursos Humanos")))
        self.bitmap_button_6.SetSize(self.bitmap_button_6.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Principal.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(3, 9, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_1, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_3, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_4, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_5, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_9, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_2, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_7, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_8, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_button_6, 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnAdministrativo(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesAdministratativo(self)
        os.system('xdg-open "ReportePostulantesAdministrativo.pdf"')
        self.Hide() #works for urls too

    def OnChofer(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesChofer(self)
        os.system('xdg-open "ReportePostulantesChofer.pdf"')
        self.Hide()
    def OnVigilante(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesVigilante(self)
        os.system('xdg-open "ReportePostulantesVigilante.pdf"')
        self.Hide()
    def OnGVentas(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesGVentas(self)
        os.system('xdg-open "ReportePostulantesGVentas.pdf"')
        self.Hide()
    def OnAVentas(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesAVentas(self)
        os.system('xdg-open "ReportePostulantesAVentas.pdf"')
        self.Hide()
    def OnAsistenteA(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesAsistenteA(self)
        os.system('xdg-open "ReportePostulantesAsistenteAd.pdf"')
        self.Hide() #works for urls too
    def OnCajero(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesCajero(self)
        os.system('xdg-open "ReportePostulantesCajero.pdf"')
        self.Hide() 
    def OnAtencionC(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesAtencionC(self)
        os.system('xdg-open "ReportePostulantesAtencionCliente.pdf"')
        self.Hide() 
    def OnRecursos(self, event):  # wxGlade: Principal.<event_handler>
        FR.PostulantesRecursos(self)
        os.system('xdg-open "ReportePostulantesRecursos.pdf"')
        self.Hide() 
# end of class Principal
